# Generated by Django 3.2.9 on 2021-11-21 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('price', models.FloatField()),
                ('qty', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_type', models.CharField(choices=[('Zasilkovna_na_adresu', 'Zásilkovna na adresu'), ('Zasilkovna_na_vydejni_misto', 'Zásilkovna na výdejní místo'), ('okoli_MH', 'Doručení v okolí Mnichova Hradiště')], default='Zasilkovna_na_adresu', max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number', models.IntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('payment_method', models.CharField(choices=[('Comgate_karta', 'Comgate - Karta'), ('Comgate_prevod', 'Comgate - Převod'), ('Hotove', 'Hotově')], default='Comgate_karta', max_length=90)),
                ('sale', models.FloatField(blank=True, null=True)),
                ('books', models.JSONField()),
                ('note', models.TextField(blank=True, max_length=1000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
