# Generated by Django 3.2.9 on 2021-11-21 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order_system', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Number',
            new_name='number',
        ),
        migrations.RemoveField(
            model_name='order',
            name='books',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='order',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='order_system.order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='dodaci_list',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='order',
            name='faktura',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order_system.shipping'),
        ),
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('zpracovava_se', 'Objednávka se zpracovává'), ('odeslana', 'Objednávka byla odeslána'), ('dokoncena', 'Objednávka byla dokončena'), ('zrusena', 'Objednávka byla zrušena')], default='zpracovava_se', max_length=90),
        ),
        migrations.AddField(
            model_name='order',
            name='through_option',
            field=models.CharField(choices=[('pemic', 'Pemic'), ('zonerpress', 'E-shop = Zoner-press')], default='pemic', max_length=90),
        ),
        migrations.AddField(
            model_name='shipping',
            name='FisD',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='qty',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(choices=[('fakturacni', 'Fakturační adresa'), ('dodaci', 'Dodací adresa')], default='fakturacni', max_length=90)),
                ('jmeno', models.CharField(max_length=200)),
                ('mesto', models.CharField(max_length=200)),
                ('ulice', models.CharField(max_length=200)),
                ('posta', models.CharField(max_length=200)),
                ('psc', models.CharField(max_length=10)),
                ('shipping', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order_system.shipping')),
            ],
        ),
    ]
