# Generated by Django 3.2.9 on 2021-11-23 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_system', '0005_alter_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='sale',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
