# Generated by Django 3.2.9 on 2021-11-23 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_system', '0006_alter_order_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
