# Generated by Django 3.2.9 on 2021-11-23 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order_system', '0007_alter_book_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order_system.order'),
        ),
    ]
