# Generated by Django 3.2.9 on 2021-11-24 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_system', '0009_auto_20211124_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='dodaci_list',
            field=models.FileField(blank=True, null=True, upload_to='dodaci_listy/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='faktura',
            field=models.FileField(blank=True, null=True, upload_to='faktury/'),
        ),
    ]
