# Generated by Django 3.2.9 on 2021-11-25 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_system', '0014_order_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='day',
            field=models.IntegerField(default=25),
        ),
    ]
